name: 09-01-Job execution
#on: push
on: workflow_dispatch
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Bye World"